sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/static/**,**/staticfiles/**,**/migrations/**,**/.venv/**,**/venv/**,**/env/**,**/*.min.js,**/*.min.css,**/tests/**,**/dist/**,**/*.zip,**/*.exe
sonar.sourceEncoding=UTF-8
