sonar.projectKey=abdullahnawfal797-cmd_school-mgmt
sonar.organization=abdullahnawfal797-cmd

# استثناء حزم الطرف الثالث والمكتبات والملفات المولدة آلياً
sonar.exclusions=**/node_modules/**,**/vendor/**,**/static/**,**/staticfiles/**,**/migrations/**,**/.venv/**,**/venv/**,**/env/**,**/*.min.js,**/*.min.css,**/dist/**,**/*.zip,**/*.exe

# حصر فحص المصادر
sonar.sources=.
sonar.sourceEncoding=UTF-8
