sonar.projectKey=abdullahnawfal797-cmd_school-mgmt
sonar.organization=abdullahnawfal797-cmd

# استثناء حزم الطرف الثالث والمكتبات والقوالب والملفات المولدة آلياً ومجلد التجارب و Dockerfile
sonar.exclusions=Dockerfile,**/scratch/**,**/templates/**,**/*.html,**/node_modules/**,**/vendor/**,**/static/**,**/staticfiles/**,**/migrations/**,**/.venv/**,**/venv/**,**/env/**,**/*.min.js,**/*.min.css,**/tests/**,**/dist/**,**/*.zip,**/*.exe

# حصر فحص المصادر
sonar.sources=.
sonar.sourceEncoding=UTF-8
