# Generated by Django 6.1 on 2026-09-02 04:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الصف الدراسي')),
                ('year', models.CharField(max_length=20, verbose_name='السنة الدراسية')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='رمز المادة')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False, verbose_name='طالب')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='معلم / مدرس')),
                ('is_parent', models.BooleanField(default=False, verbose_name='ولي أمر')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=100, verbose_name='رقم الكتاب الرسمي')),
                ('doc_date', models.DateField(verbose_name='تاريخ الكتاب')),
                ('doc_type', models.CharField(choices=[('issued', 'كتاب صادر'), ('received', 'كتاب وارد'), ('dept_reply', 'إجابات ومخاطبات القسم'), ('directorate', 'المديرية العامة للتربية'), ('ministry', 'وزارة التربية'), ('circular', 'أمر إداري / تعميم'), ('other', 'أخرى')], default='received', max_length=30, verbose_name='نوع الكتاب')),
                ('sender_receiver', models.CharField(max_length=200, verbose_name='الجهة الصادرة / المستلمة')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع / خلاصة الكتاب')),
                ('file', models.FileField(blank=True, null=True, upload_to='official_documents/%Y/%m/', verbose_name='الملف المرفق / الصورة (PDF/Image)')),
                ('status', models.CharField(choices=[('pending', 'قيد المتابعة / الإجراء'), ('completed', 'تم الإنجاز والرد'), ('archived', 'مؤرشف للحفظ')], default='pending', max_length=20, verbose_name='حالة المتابعة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات / نص الإجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسجل')),
            ],
            options={
                'verbose_name': 'كتاب رسمي / أرشيف',
                'verbose_name_plural': 'سجل الكتب والمخاطبات الرسمية',
                'ordering': ['-doc_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='عنوان السكن')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'ولي أمر',
                'verbose_name_plural': 'أولياء الأمور',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشعبة')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.schoolclass', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'شعبة دراسية',
                'verbose_name_plural': 'الشعب الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الوطني / الهوية')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='تاريخ التولد')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schoolclass', verbose_name='الصف الحالي')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parent', verbose_name='ولي الأمر')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.section', verbose_name='الشعبة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب الطالب')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('due', 'مستحق الدفع'), ('paid', 'مدفوع')], default='due', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'فاتورة رسوم',
                'verbose_name_plural': 'سجل الفواتير والرسوم',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='العام الدراسي')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='حالة القيد')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass', verbose_name='الصف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'قيد وتسجيل',
                'verbose_name_plural': 'سجل القيود',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='مدرس', max_length=100, verbose_name='العنوان الوظيفي')),
                ('statistical_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الإحصائي / الوظيفي')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المباشرة')),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject', verbose_name='المواد التي يدرسها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المعلم')),
            ],
            options={
                'verbose_name': 'معلم / مدرس',
                'verbose_name_plural': 'الكادر التدريسي',
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass', verbose_name='الصف الدراسي')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.section', verbose_name='الشعبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'حصة دراسية',
                'verbose_name_plural': 'جدول الحصص الأسبوعي',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'مجاز')], max_length=10, verbose_name='حالة الحضور')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسجل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حضور وغياب',
                'verbose_name_plural': 'سجل الحضور والغياب',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20, verbose_name='العام الدراسي')),
                ('first_term_month1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الفصل الأول - شهر 1')),
                ('first_term_month2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الفصل الأول - شهر 2')),
                ('first_term_effort', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='سعي الفصل الأول')),
                ('midyear_exam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='امتحان نصف السنة')),
                ('second_term_month1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الفصل الثاني - شهر 1')),
                ('second_term_month2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الفصل الثاني - شهر 2')),
                ('second_term_effort', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='سعي الفصل الثاني')),
                ('annual_effort', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='السعي السنوي')),
                ('final_exam_round1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الامتحان النهائي - الدور الأول')),
                ('final_exam_round2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الامتحان النهائي - الدور الثاني')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة النهائية قبل القرار')),
                ('decision_marks', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='درجات القرار الممنوحة')),
                ('final_grade_after_decision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة النهائية بعد القرار')),
                ('status', models.CharField(choices=[('pending', 'قيد الإنجاز'), ('passed', 'ناجح'), ('passed_by_decision', 'ناجح بالقرار'), ('supplementary', 'مكمل'), ('failed', 'راسب')], default='pending', max_length=20, verbose_name='النتيجة النهائية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'سجل درجات',
                'verbose_name_plural': 'سجل الدرجات (النظام العراقي)',
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
    ]
