# Generated by Django 6.1 on 2026-09-02 05:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='السنة الدراسية')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_current', models.BooleanField(default=False, verbose_name='السنة الحالية')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشفة ومغلقة')),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم / رقم القاعة')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع / الجناح')),
                ('capacity', models.PositiveIntegerField(verbose_name='السعة الكلية للمقاعد')),
                ('rows_count', models.PositiveIntegerField(default=5, verbose_name='عدد الصفوف')),
                ('cols_count', models.PositiveIntegerField(default=6, verbose_name='عدد الأعمدة')),
            ],
            options={
                'verbose_name': 'قاعة امتحانية',
                'verbose_name_plural': 'القاعات الامتحانية',
            },
        ),
        migrations.CreateModel(
            name='OfficialLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان القالب')),
                ('template_type', models.CharField(choices=[('service_confirmation', 'تأييد استمرار بالخدمة'), ('grades_confirmation', 'تأييد درجات طالب'), ('dept_reply', 'إجابة كتاب رسمي'), ('general', 'كتاب رسمي عام')], max_length=30, verbose_name='نوع القالب')),
                ('content', models.TextField(help_text='المتغيرات المتاحة: {{student_name}}, {{class_name}}, {{reg_number}}, {{teacher_name}}, {{date}}, {{school_name}}', verbose_name='نص القالب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قالب كتاب رسمي',
                'verbose_name_plural': 'قوالب الكتب والتأييدات الرسمية',
            },
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['level_order', 'name'], 'verbose_name': 'صف دراسي', 'verbose_name_plural': 'الصفوف الدراسية'},
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='body_content',
            field=models.TextField(blank=True, null=True, verbose_name='نص الكتاب / الرد الكامل'),
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='incoming_doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الوارد المربوط'),
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='incoming_doc_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الكتاب الوارد المربوط'),
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='outgoing_reply_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم كتاب الإجابة الصادر'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='is_final_stage',
            field=models.BooleanField(default=False, verbose_name='مرحلة منتهية (تخرج)'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='level_order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتيب المرحلة'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_classes', to='core.schoolclass', verbose_name='الصف اللاحق للترحيل'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المباشرة'),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم القيد العام'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('active', 'مستمر بالدوام'), ('graduated', 'خريج'), ('transferred', 'منقول'), ('dismissed', 'مفصول / تارك')], default='active', max_length=20, verbose_name='حالة الطالب'),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان الدورة الامتحانية')),
                ('session_type', models.CharField(choices=[('mid_year', 'امتحانات نصف السنة'), ('final_round1', 'الامتحانات النهائية - الدور الأول'), ('final_round2', 'الامتحانات النهائية - الدور الثاني')], max_length=30, verbose_name='نوع الامتحان')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear', verbose_name='السنة الدراسية')),
                ('halls', models.ManyToManyField(blank=True, to='core.examhall', verbose_name='القاعات المعتمدة')),
            ],
            options={
                'verbose_name': 'دورة امتحانية',
                'verbose_name_plural': 'الدورات الامتحانية',
            },
        ),
        migrations.CreateModel(
            name='ExamSeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='رقم الجلوس / المقعد')),
                ('desk_row', models.PositiveIntegerField(verbose_name='الصف الأفقي')),
                ('desk_col', models.PositiveIntegerField(verbose_name='العمود')),
                ('exam_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.examhall', verbose_name='القاعة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seats', to='core.student', verbose_name='الطالب')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.examsession', verbose_name='الدورة الامتحانية')),
            ],
            options={
                'verbose_name': 'توزيع مقعد امتحاني',
                'verbose_name_plural': 'توزيع مقاعد الامتحانات',
                'ordering': ['exam_hall', 'seat_number'],
                'unique_together': {('exam_session', 'exam_hall', 'seat_number'), ('exam_session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='الشعبة')),
                ('result_status', models.CharField(choices=[('passed', 'ناجح'), ('failed', 'راسب'), ('graduated', 'تخرج')], default='passed', max_length=20, verbose_name='النتيجة النهائية')),
                ('general_average', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='المعدل العام')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear', verbose_name='السنة الدراسية')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass', verbose_name='الصف الدراسي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'أرشيف أكاديمي لطالب',
                'verbose_name_plural': 'أرشيف المسيرة الدراسية للطلاب',
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
