# Generated by Django 6.1 on 2026-09-02 06:26

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academicyear_examhall_officiallettertemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='إعدادية الفراهيدي للبنين', max_length=255, verbose_name='اسم المدرسة')),
                ('director_name', models.CharField(default='أحمد شاكر محمود', max_length=255, verbose_name='اسم مدير المدرسة')),
                ('directorate', models.CharField(default='المديرية العامة لتربية صلاح الدين', max_length=255, verbose_name='المديرية العامة للتربية')),
                ('sub_directorate', models.CharField(default='قسم تربية بيجي', max_length=255, verbose_name='القسم / الممثلية')),
                ('school_gender', models.CharField(choices=[('boys', 'بنين (ذكور)'), ('girls', 'بنات (إناث)'), ('mixed', 'مختلط')], default='boys', max_length=20, verbose_name='جنس المدرسة')),
                ('school_level', models.CharField(choices=[('primary', 'ابتدائية'), ('intermediate', 'متوسطة'), ('preparatory', 'إعدادية'), ('secondary', 'ثانوية (متوسطة + إعدادية)')], default='secondary', max_length=20, verbose_name='المرحلة الدراسية')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='لوغو المدرسة')),
                ('is_subscription_active', models.BooleanField(default=True, verbose_name='حالة الاشتراك (مفعل/معطل)')),
                ('subscription_end_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ نهاية الاشتراك')),
                ('license_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='مفتاح الترخيص البرمجي')),
            ],
            options={
                'verbose_name': 'إعدادات وهوية المدرسة والترخيص',
                'verbose_name_plural': 'إعدادات وهوية المدرسة والترخيص',
            },
        ),
        migrations.AlterField(
            model_name='grade',
            name='annual_effort',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='السعي السنوي'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='decision_marks',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='درجات القرار الممنوحة'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_exam_round1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الامتحان النهائي - الدور الأول'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_exam_round2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الامتحان النهائي - الدور الثاني'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الدرجة النهائية قبل القرار'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_grade_after_decision',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الدرجة النهائية بعد القرار'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='first_term_effort',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='سعي الفصل الأول'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='first_term_month1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الفصل الأول - شهر 1'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='first_term_month2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الفصل الأول - شهر 2'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midyear_exam',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='امتحان نصف السنة'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='second_term_effort',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='سعي الفصل الثاني'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='second_term_month1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الفصل الثاني - شهر 1'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='second_term_month2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الفصل الثاني - شهر 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='المبلغ (صحيح)'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='official_documents/%Y/%m/', verbose_name='الملف المرفق'),
        ),
        migrations.AlterField(
            model_name='officiallettertemplate',
            name='content',
            field=models.TextField(help_text='المتغيرات: {{student_name}}, {{class_name}}, {{reg_number}}, {{teacher_name}}, {{date}}, {{school_name}}', verbose_name='نص القالب'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='year',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='studentacademichistory',
            name='general_average',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, verbose_name='المعدل العام (صحيح)'),
        ),
    ]
