# Generated by Django 6.1 on 2026-09-02 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolsettings_alter_grade_annual_effort_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableslot',
            options={'ordering': ['day', 'period'], 'verbose_name': 'حصة دراسية', 'verbose_name_plural': 'جدول الحصص الأسبوعي'},
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='daily_periods_count',
            field=models.PositiveIntegerField(default=6, verbose_name='عدد الحصص اليومية المعتمدة'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='حصة فعالة'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='period',
            field=models.IntegerField(choices=[(1, 'الحصة الأولى'), (2, 'الحصة الثانية'), (3, 'الحصة الثالثة'), (4, 'الحصة الرابعة'), (5, 'الحصة الخامسة'), (6, 'الحصة السادسة'), (7, 'الحصة السابعة'), (8, 'الحصة الثامنة')], default=1, verbose_name='رقم الحصة'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='room',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='القاعة / المختبر'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='core.schoolclass', verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='core.section', verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='core.subject', verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='core.teacher', verbose_name='المدرس'),
        ),
        migrations.CreateModel(
            name='TeacherQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_periods', models.PositiveIntegerField(default=24, verbose_name='الحصص المطلوبة أسبوعياً')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='core.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'نصاب معلم',
                'verbose_name_plural': 'نصاب المعلمين الأسبوعي',
            },
        ),
        migrations.CreateModel(
            name='TimetableSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الاستبدال')),
                ('reason', models.CharField(blank=True, default='إجازة رسمية / طارئة', max_length=200, verbose_name='سبب الاستبدال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_substitutions', to='core.teacher', verbose_name='المعلم الغائب')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='core.timetableslot', verbose_name='الحصة المستبدلة')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_substitutions', to='core.teacher', verbose_name='المعلم البديل (الاحتياط)')),
            ],
            options={
                'verbose_name': 'استبدال حصة / احتياط',
                'verbose_name_plural': 'سجل الاستبدالات والاحتياط اليومي',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الإصدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات الإصدار')),
                ('snapshot_data', models.JSONField(default=dict, verbose_name='بيانات النسخة')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicyear', verbose_name='العام الدراسي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'إصدار جدول معتمد',
                'verbose_name_plural': 'أرشيف إصدارات الجداول المعتمدة',
                'ordering': ['-created_at'],
            },
        ),
    ]
