# Generated by Django 6.1 on 2026-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_timetableslot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='year',
        ),
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=40, verbose_name='الطاقة الاستيعابية'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(default='2026-2027', max_length=20, verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(default='2026-2027', max_length=20, verbose_name='العام الدراسي'),
        ),
    ]
