# Generated by Django 6.1 on 2026-09-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_schoolclass_year_section_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='director_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم مدير المدرسة'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='directorate',
            field=models.CharField(default='المديرية العامة للتربية', max_length=255, verbose_name='المديرية العامة للتربية'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_name',
            field=models.CharField(default='اسم المؤسسة التعليمية', max_length=255, verbose_name='اسم المدرسة'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='sub_directorate',
            field=models.CharField(default='قسم التربية', max_length=255, verbose_name='القسم / الممثلية'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الاشتراك'),
        ),
    ]
