# Generated by Django 4.2.30 on 2026-09-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schoolsettings_director_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'مجاز')], db_index=True, max_length=10, verbose_name='حالة الحضور'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(db_index=True, default='2026-2027', max_length=20, verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الإنجاز'), ('passed', 'ناجح'), ('passed_by_decision', 'ناجح بالقرار'), ('supplementary', 'مكمل'), ('failed', 'راسب')], db_index=True, default='pending', max_length=20, verbose_name='النتيجة النهائية'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='level_order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='ترتيب المرحلة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='الرقم الوطني / الهوية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('active', 'مستمر بالدوام'), ('graduated', 'خريج'), ('transferred', 'منقول'), ('dismissed', 'مفصول / تارك')], db_index=True, default='active', max_length=20, verbose_name='حالة الطالب'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.IntegerField(choices=[(0, 'الأحد'), (1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], db_index=True, verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='حصة فعالة'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='period',
            field=models.IntegerField(choices=[(1, 'الحصة الأولى'), (2, 'الحصة الثانية'), (3, 'الحصة الثالثة'), (4, 'الحصة الرابعة'), (5, 'الحصة الخامسة'), (6, 'الحصة السادسة'), (7, 'الحصة السابعة'), (8, 'الحصة الثامنة')], db_index=True, default=1, verbose_name='رقم الحصة'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='core_attend_student_931c39_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='core_attend_date_7783ad_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'academic_year'], name='core_grade_student_09fa1b_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['academic_year', 'subject'], name='core_grade_academi_e9fda4_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['academic_year', 'status'], name='core_grade_academi_bd3c21_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['level_order', 'name'], name='core_school_level_o_059ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_class', 'is_deleted'], name='core_studen_current_2022ed_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_class', 'section', 'is_deleted'], name='core_studen_current_23ffd4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_status', 'is_deleted'], name='core_studen_student_084b86_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['school_class', 'day', 'period'], name='core_timeta_school__8e01d1_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['teacher', 'day', 'period'], name='core_timeta_teacher_697ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['day', 'period', 'is_active'], name='core_timeta_day_93e7d3_idx'),
        ),
    ]
