# Generated by Django 4.2.30 on 2026-09-04 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attendance_date_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_documents', to='core.student', verbose_name='الطالب المعني'),
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_documents', to='core.teacher', verbose_name='المعلم المعني'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='is_first_run_completed',
            field=models.BooleanField(default=False, verbose_name='اكتمل معالج الإعداد الأول'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='license_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='توقيع التشفير لحماية الترخيص'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='doc_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الكتاب'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='doc_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='رقم الكتاب الرسمي'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='doc_type',
            field=models.CharField(choices=[('issued', 'كتاب صادر'), ('received', 'كتاب وارد'), ('student_cert', 'وثائق وتأييدات الطلبة'), ('circular', 'أمر إداري / تعميم'), ('dept_reply', 'إجابات ومخاطبات القسم'), ('directorate', 'المديرية العامة للتربية'), ('ministry', 'وزارة التربية'), ('other', 'أخرى')], db_index=True, default='received', max_length=30, verbose_name='نوع الكتاب'),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المتابعة / الإجراء'), ('completed', 'تم الإنجاز والرد'), ('archived', 'مؤرشف للحفظ')], default='archived', max_length=20, verbose_name='حالة المتابعة'),
        ),
        migrations.AddIndex(
            model_name='officialdocument',
            index=models.Index(fields=['doc_type', 'doc_date'], name='core_offici_doc_typ_c09b76_idx'),
        ),
        migrations.AddIndex(
            model_name='officialdocument',
            index=models.Index(fields=['doc_number', 'doc_date'], name='core_offici_doc_num_80d4a7_idx'),
        ),
    ]
