# Generated by Django 4.2.30 on 2026-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_officialdocument_student_officialdocument_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_level',
            field=models.CharField(choices=[('primary', 'ابتدائية (الصفوف 1 - 6)'), ('intermediate', 'متوسطة (الأول - الثالث متوسط)'), ('preparatory', 'إعدادية (الرابع - السادس إعدادي)'), ('secondary', 'ثانوية (متوسطة + إعدادية)'), ('all_stages', 'شاملة / ثانوية متكاملة (ابتدائية + متوسطة + إعدادية)')], default='secondary', max_length=20, verbose_name='المرحلة الدراسية'),
        ),
    ]
