# Generated by Django 4.2.30 on 2026-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_schoolsettings_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='examhall',
            name='desk_type',
            field=models.CharField(choices=[('single', 'مقعد فردي (طالب واحد)'), ('double', 'مقعد ثنائي (طالبان)')], default='single', max_length=20, verbose_name='طبيعة المقعد / الرحلة'),
        ),
        migrations.AddField(
            model_name='examhall',
            name='desks_per_line',
            field=models.PositiveIntegerField(default=6, verbose_name='عدد الرحلات في كل خط'),
        ),
        migrations.AddField(
            model_name='examhall',
            name='lines_count',
            field=models.PositiveIntegerField(default=3, verbose_name='عدد الخطوط في القاعة'),
        ),
        migrations.AlterField(
            model_name='examhall',
            name='capacity',
            field=models.PositiveIntegerField(default=18, verbose_name='السعة الكلية للمقاعد'),
        ),
        migrations.AlterField(
            model_name='examhall',
            name='cols_count',
            field=models.PositiveIntegerField(default=3, verbose_name='عدد الأعمدة'),
        ),
        migrations.AlterField(
            model_name='examhall',
            name='rows_count',
            field=models.PositiveIntegerField(default=6, verbose_name='عدد الصفوف'),
        ),
    ]
