# Generated by Django 4.2.30 on 2026-09-04 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_examhall_desk_type_examhall_desks_per_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='installation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ تثبيت المنظومة'),
        ),
    ]
