# Generated by Django 4.2.30 on 2026-09-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_schoolsettings_installation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='ministry_school_code',
            field=models.CharField(default='', max_length=50, verbose_name='الرمز الإحصائي الوزاري للمدرسة (كود التربية)'),
        ),
    ]
