# Generated by Django 4.2.30 on 2026-09-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schoolsettings_ministry_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_classes',
            field=models.ManyToManyField(blank=True, to='core.schoolclass', verbose_name='الصفوف والمراحل التي يدرسها'),
        ),
    ]
