# Generated by Django 4.2.30 on 2026-09-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teacher_school_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'id'], 'verbose_name': 'مادة دراسية', 'verbose_name_plural': 'المواد الدراسية'},
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='المرحلة / الصف الدراسي'),
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='الترتيب'),
        ),
    ]
