# Generated by Django 5.1.15 on 2026-09-05 22:06

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_subject_options_subject_grade_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGrade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('academic_year', models.CharField(db_index=True, default='2026-2027', max_length=20, verbose_name='العام الدراسي')),
                ('first_term_month1', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الفصل الأول - شهر 1')),
                ('first_term_month2', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الفصل الأول - شهر 2')),
                ('first_term_effort', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='سعي الفصل الأول')),
                ('midyear_exam', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='امتحان نصف السنة')),
                ('second_term_month1', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الفصل الثاني - شهر 1')),
                ('second_term_month2', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الفصل الثاني - شهر 2')),
                ('second_term_effort', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='سعي الفصل الثاني')),
                ('annual_effort', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='السعي السنوي')),
                ('final_exam_round1', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الامتحان النهائي - الدور الأول')),
                ('final_exam_round2', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الامتحان النهائي - الدور الثاني')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الدرجة النهائية قبل القرار')),
                ('decision_marks', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='درجات القرار الممنوحة')),
                ('final_grade_after_decision', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='الدرجة النهائية بعد القرار')),
                ('status', models.CharField(choices=[('pending', 'قيد الإنجاز'), ('passed', 'ناجح'), ('passed_by_decision', 'ناجح بالقرار'), ('supplementary', 'مكمل'), ('failed', 'راسب')], db_index=True, default='pending', max_length=20, verbose_name='النتيجة النهائية')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'historical سجل درجات',
                'verbose_name_plural': 'historical سجل الدرجات (النظام العراقي)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSchoolClass',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الصف الدراسي')),
                ('level_order', models.PositiveIntegerField(db_index=True, default=1, verbose_name='ترتيب المرحلة')),
                ('is_final_stage', models.BooleanField(default=False, verbose_name='مرحلة منتهية (تخرج)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('next_class', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.schoolclass', verbose_name='الصف اللاحق للترحيل')),
            ],
            options={
                'verbose_name': 'historical صف دراسي',
                'verbose_name_plural': 'historical الصفوف الدراسية',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشعبة')),
                ('capacity', models.PositiveIntegerField(default=40, verbose_name='الطاقة الاستيعابية')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.schoolclass', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'historical شعبة دراسية',
                'verbose_name_plural': 'historical الشعب الدراسية',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم القيد العام')),
                ('admission_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المباشرة')),
                ('student_status', models.CharField(choices=[('active', 'مستمر بالدوام'), ('graduated', 'خريج'), ('transferred', 'منقول'), ('dismissed', 'مفصول / تارك')], db_index=True, default='active', max_length=20, verbose_name='حالة الطالب')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='الرقم الوطني / الهوية')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='تاريخ التولد')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('current_class', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.schoolclass', verbose_name='الصف الحالي')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.parent', verbose_name='ولي الأمر')),
                ('section', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.section', verbose_name='الشعبة')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='حساب الطالب')),
            ],
            options={
                'verbose_name': 'historical طالب',
                'verbose_name_plural': 'historical الطلاب',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSubject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='رمز المادة')),
                ('grade_level', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='المرحلة / الصف الدراسي')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical مادة دراسية',
                'verbose_name_plural': 'historical المواد الدراسية',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
