# Generated by Django 5.1.15 on 2026-09-05 23:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicalgrade_historicalschoolclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='اسم المستخدم')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='العملية')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='النموذج')),
                ('object_id', models.CharField(db_index=True, max_length=100, verbose_name='معرف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='وصف الكائن')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='القيمة السابقة')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='القيمة الجديدة')),
                ('edit_reason', models.TextField(blank=True, null=True, verbose_name='سبب التعديل')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='بصمة الجهاز')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ والوقت')),
                ('previous_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64, verbose_name='بصمة السجل السابق')),
                ('current_hash', models.CharField(db_index=True, max_length=64, verbose_name='بصمة التشفير الحالية')),
            ],
            options={
                'verbose_name': 'سجل تدقيق تشفيري',
                'verbose_name_plural': 'سلسلة التدقيق التشفيرية الموثقة',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=60, verbose_name='نوع الحدث')),
                ('severity', models.CharField(choices=[('INFO', 'معلوماتي'), ('WARNING', 'تحذيري'), ('HIGH', 'عالي الخطورة'), ('CRITICAL', 'حرج للغاية')], db_index=True, default='INFO', max_length=20, verbose_name='درجة الخطورة')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='اسم المستخدم')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='عنوان IP')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='بصمة الجهاز')),
                ('details', models.TextField(blank=True, verbose_name='تفاصيل الحدث')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت الحدث')),
            ],
            options={
                'verbose_name': 'سجل حدث أمني',
                'verbose_name_plural': 'سجل أحداث الأمان',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='amendment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب التعديل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='grade',
            name='approval_state',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مرفوعة للاعتماد'), ('APPROVED', 'معتمدة رسمياً'), ('LOCKED', 'مقفلة نهائياً'), ('AMENDED', 'معدلة استثنائياً')], db_index=True, default='APPROVED', max_length=20, verbose_name='حالة الاعتماد المؤسسي'),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='هل الدرجة مقفلة'),
        ),
        migrations.AddField(
            model_name='grade',
            name='last_amended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='grade',
            name='last_amended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amended_grades', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالتعديل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='grade',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقفال'),
        ),
        migrations.AddField(
            model_name='grade',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_grades', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالإقفال'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='amendment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب التعديل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='approval_state',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مرفوعة للاعتماد'), ('APPROVED', 'معتمدة رسمياً'), ('LOCKED', 'مقفلة نهائياً'), ('AMENDED', 'معدلة استثنائياً')], db_index=True, default='APPROVED', max_length=20, verbose_name='حالة الاعتماد المؤسسي'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='هل الدرجة مقفلة'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='last_amended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='last_amended_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالتعديل الاستثنائي'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقفال'),
        ),
        migrations.AddField(
            model_name='historicalgrade',
            name='locked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالإقفال'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='activation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التفعيل الفعلي'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='last_known_valid_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر وقت نظام صالح وموثق'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='license_code_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف كود الترخيص الفريد'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='license_status',
            field=models.CharField(default='ACTIVE', max_length=30, verbose_name='حالة الترخيص المؤسسي'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='subscription_plan',
            field=models.CharField(default='MONTHLY_30_DAYS', max_length=50, verbose_name='باقة الاشتراك'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='time_tamper_detected',
            field=models.BooleanField(default=False, verbose_name='هل تم اكتشاف تلاعب زمني'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدير النظام العام (Super Administrator)'), ('school_admin', 'مدير النظام المدرسي (School Administrator)'), ('principal', 'مدير المدرسة (Principal)'), ('assistant_principal', 'معاون المدير (Assistant Principal)'), ('teacher', 'معلم / مدرس (Teacher)'), ('grades_officer', 'مسؤول الدرجات والامتحانات (Grades Officer)'), ('accountant', 'المحاسب المالي (Accountant)'), ('registrar', 'مسؤول التسجيل وشؤون الطلبة (Registrar)'), ('viewer', 'مستعرض / قارئ فقط (Viewer)')], db_index=True, default='school_admin', max_length=30, verbose_name='الدور المؤسسي'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['academic_year', 'approval_state'], name='core_grade_academi_7896e2_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['academic_year', 'is_locked'], name='core_grade_academi_9961b7_idx'),
        ),
        migrations.AddField(
            model_name='auditchainrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='securityeventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
