# Generated by Django 5.1.15 on 2026-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditchainrecord_securityeventlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubject',
            name='weekly_periods',
            field=models.PositiveIntegerField(default=2, verbose_name='عدد الحصص الأسبوعية (النصاب الوزاري)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='weekly_periods',
            field=models.PositiveIntegerField(default=2, verbose_name='عدد الحصص الأسبوعية (النصاب الوزاري)'),
        ),
    ]
