# Generated by Django 5.1.15 on 2026-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_historicalsubject_weekly_periods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='جنس الطالب'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='جنس الطالب'),
        ),
    ]
