# Generated by Django 5.1.15 on 2026-09-09 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historicalstudent_gender_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(blank=True, default='', max_length=150, verbose_name='عنوان الامتحان')),
                ('exam_date', models.DateField(verbose_name='تاريخ الامتحان')),
                ('exam_time', models.CharField(blank=True, default='', max_length=40, verbose_name='الوقت')),
                ('topics', models.TextField(blank=True, default='', verbose_name='المواضيع المطلوبة (من صفحة إلى صفحة)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='أُعلن بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت النشر')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_announcements', to='core.schoolclass', verbose_name='الصف')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_announcements', to='core.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'إعلان امتحان',
                'verbose_name_plural': 'إعلانات الامتحانات الشهرية',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('TO_SCHOOL', 'إلى المدرسة'), ('FROM_SCHOOL', 'من المدرسة')], default='TO_SCHOOL', max_length=20, verbose_name='الاتجاه')),
                ('body', models.TextField(verbose_name='النص')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.parent', verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'محادثات أولياء الأمور مع الإدارة',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TRANSFER', 'طلب نقل الطالب'), ('GRADE_ATTESTATION', 'تأييد درجات'), ('SERVICE_ATTESTATION', 'تأييد استمرارية خدمة'), ('TRANSCRIPT', 'كشف درجات / شهادة'), ('OTHER', 'طلب آخر')], max_length=30, verbose_name='نوع الطلب')),
                ('details', models.TextField(blank=True, default='', verbose_name='التفاصيل')),
                ('status', models.CharField(choices=[('SUBMITTED', 'وصل الطلب'), ('IN_PROGRESS', 'جاري تحضير الكتاب'), ('READY', 'الكتاب جاهز للتسليم'), ('DENIED', 'مرفوض')], default='SUBMITTED', max_length=20, verbose_name='الحالة')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='ملاحظة الإدارة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('letter_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_requests', to='core.officialdocument', verbose_name='الكتاب الصادر')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='core.parent', verbose_name='ولي الأمر')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='core.student', verbose_name='الطالب المعني')),
            ],
            options={
                'verbose_name': 'طلب ولي أمر',
                'verbose_name_plural': 'طلبات أولياء الأمور والكتب',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GENERAL', 'إعلان عام'), ('CALL_IN', 'استدعاء ولي أمر'), ('MEETING', 'اجتماع أولياء الأمور'), ('EXAM', 'امتحان'), ('OTHER', 'إشعار آخر')], default='GENERAL', max_length=20, verbose_name='النوع')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='النص')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='أُنشئ بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='core.schoolclass', verbose_name='الصف (إن كان خاصاً بصف)')),
            ],
            options={
                'verbose_name': 'إشعار للإدارة',
                'verbose_name_plural': 'إشعارات الإدارة لأولياء الأمور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('PRAISE', 'سلوك إيجابي / تشجيع'), ('CONCERN', 'ملاحظة سلوكية'), ('WARNING', 'تنبيه / إنذار'), ('CALL_IN', 'استدعاء ولي الأمر')], default='CONCERN', max_length=20, verbose_name='نوع الملاحظة')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_records', to='core.teacher', verbose_name='مُسجّل بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل سلوكي',
                'verbose_name_plural': 'السجل السلوكي للطلاب',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
