# Generated by Django 5.1.15 on 2026-09-11 15:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_examannouncement_parentchatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='school',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.schoolsettings', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الاشتراك المالي'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolsettings', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط في المدرسة'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.schoolsettings', verbose_name='المدرسة'),
        ),
        migrations.CreateModel(
            name='SchoolSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الدفعة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم الذي سجل الدفعة')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='core.schoolsettings', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'دفعة اشتراك مدرسة',
                'verbose_name_plural': 'سجل دفعات اشتراكات المدارس',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
