# Generated by Django 5.1.15 on 2026-09-11 15:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_historicalstudent_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubscriptionpayment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='core.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.CreateModel(
            name='SchoolYearSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='قيمة الاشتراك المستحق')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصومات والتسويات المعتمدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة الاشتراك السنوي (مفعل/معطل)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ استحقاق السداد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات العقد أو الاشتراك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subscriptions', to='core.academicyear', verbose_name='السنة الدراسية')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_subscriptions', to='core.schoolsettings', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'اشتراك المدرسة السنوي',
                'verbose_name_plural': 'اشتراكات المدارس السنوية',
                'ordering': ['-academic_year__start_date', '-created_at'],
                'unique_together': {('school', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SchoolPaymentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('discount', 'خصم مالي ممنوح'), ('waiver', 'إعفاء أو تسوية خاصة'), ('scholarship', 'منحة / تسوية شرفية'), ('other', 'أخرى')], default='discount', max_length=30, verbose_name='نوع التسوية/الخصم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الخصم/التسوية')),
                ('reason', models.TextField(blank=True, default='', verbose_name='سبب وتفاصيل الخصم أو التسوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_adjustments', to='core.academicyear', verbose_name='السنة الدراسية')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول المعتمد')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_adjustments', to='core.schoolsettings', verbose_name='المدرسة')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.schoolyearsubscription', verbose_name='الاشتراك السنوي')),
            ],
            options={
                'verbose_name': 'خصم / تسوية مالية للمدرسة',
                'verbose_name_plural': 'سجل الخصومات والتسويات المالية للمدارس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schoolsubscriptionpayment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.schoolyearsubscription', verbose_name='الاشتراك السنوي المستهدف'),
        ),
    ]
