# Generated by Django 5.1.15 on 2026-09-09 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_examannouncement_parentchatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(default='الصف الأول', max_length=100, verbose_name='الشعبة / الصف')),
                ('subject', models.CharField(default='الرياضيات', max_length=100, verbose_name='المادة')),
                ('title', models.CharField(default='', max_length=200, verbose_name='عنوان الواجب')),
                ('description', models.TextField(default='', verbose_name='تفاصيل الواجب')),
                ('due_date', models.CharField(blank=True, default='', max_length=50, verbose_name='موعد التسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'واجب منزلي',
                'verbose_name_plural': 'الواجبات المنزلية',
            },
        ),
        migrations.CreateModel(
            name='SchoolNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(default='', verbose_name='المحتوى')),
                ('category', models.CharField(default='تعميم إداري', max_length=50, verbose_name='التصنيف')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تعميم أو خبر مدرسي',
                'verbose_name_plural': 'التعاميم والأخبار المدرسية',
            },
        ),
        migrations.CreateModel(
            name='AuditTrailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=150, verbose_name='الإجراء')),
                ('entity_name', models.CharField(default='', max_length=100, verbose_name='الكيان')),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل تدقيق العمليات',
                'verbose_name_plural': 'سجل تدقيق العمليات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('body', models.TextField(default='')),
                ('notification_type', models.CharField(default='GENERAL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار فوري',
                'verbose_name_plural': 'الإشعارات الفورية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'المالك والمشرف العام'), ('MANAGER', 'مدير المدرسة'), ('TEACHER', 'معلم'), ('PARENT', 'ولي أمر')], default='PARENT', max_length=20, verbose_name='الدور')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الهاتف')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد رسمياً')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم المنظومة',
                'verbose_name_plural': 'ملفات مستخدمي المنظومة',
            },
        ),
        migrations.CreateModel(
            name='StudentActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(default='', max_length=64, unique=True, verbose_name='كود التفعيل')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('ACTIVE', 'نشط وسارٍ'), ('EXPIRED', 'منتهي الصلاحية'), ('REJECTED', 'مرفوض'), ('SUSPENDED', 'معلق')], default='PENDING', max_length=20, verbose_name='حالة الاشتراك')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('decision_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='سبب الرفض')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='صاحب القرار')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.student', verbose_name='الطالب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='mobile_api.userprofile', verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'تفعيل واشتراك الطالب',
                'verbose_name_plural': 'تفعيلات واشتراكات الطلبة',
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(default='شهري', max_length=50, verbose_name='نوع الامتحان')),
                ('month1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('month2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('daily', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة لدى المعلم'), ('SUBMITTED', 'مرسلة للمراجعة'), ('APPROVED', 'معتمدة ومصادقة من الإدارة'), ('REJECTED', 'معادة للتدقيق')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_grades', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_grades', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_grades', to='mobile_api.userprofile')),
            ],
            options={
                'verbose_name': 'سجل رصد واعتماد الدرجات',
                'verbose_name_plural': 'سجلات رصد واعتماد الدرجات',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='رقم المعاملة')),
                ('doc_type', models.CharField(default='تأييد استمرار بالدوام', max_length=100, verbose_name='نوع المعاملة')),
                ('destination', models.CharField(blank=True, default='إدارة المدرسة', max_length=200, verbose_name='الجهة الموجه إليها')),
                ('details', models.TextField(blank=True, default='', verbose_name='تفاصيل إضافية')),
                ('status', models.CharField(choices=[('SUBMITTED', 'تم الإرسال'), ('UNDER_REVIEW', 'قيد التدقيق'), ('APPROVED', 'تمت الموافقة وجاهز للاستلام'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'تم التسليم')], default='SUBMITTED', max_length=20)),
                ('admin_response', models.TextField(blank=True, default='', verbose_name='رد الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='core.student')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='mobile_api.userprofile')),
            ],
            options={
                'verbose_name': 'طلب وثيقة أو معاملة رسمية',
                'verbose_name_plural': 'طلبات الوثائق والمعاملات الرسمية',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تم تأكيد الربط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_relations', to='core.student', verbose_name='الطالب')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='mobile_api.userprofile', verbose_name='ولي الأمر')),
            ],
            options={
                'verbose_name': 'علاقة ولي الأمر بالطالب',
                'verbose_name_plural': 'علاقات أولياء الأمور بالطلبة',
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
