# Generated by Django 5.1.15 on 2026-09-11 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_historicalstudent_school_and_more'),
        ('mobile_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivation',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل الفعلي'),
        ),
        migrations.AddField(
            model_name='studentactivation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_activations', to=settings.AUTH_USER_MODEL, verbose_name='من أنشأ الكود'),
        ),
        migrations.AddField(
            model_name='studentactivation',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='تم استخدام الكود'),
        ),
        migrations.AddField(
            model_name='studentactivation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.schoolsettings', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_profiles', to='core.schoolsettings', verbose_name='المدرسة'),
        ),
    ]
