# Generated by Django 5.1.15 on 2026-09-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_schoolsubscriptionpayment_academic_year_and_more'),
        ('mobile_api', '0002_studentactivation_activated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivation',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activations', to='core.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AddIndex(
            model_name='studentactivation',
            index=models.Index(fields=['student', 'academic_year'], name='mobile_api__student_fe1485_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivation',
            index=models.Index(fields=['status', 'academic_year'], name='mobile_api__status_9ccd99_idx'),
        ),
    ]
