# Generated by Django 5.1.15 on 2026-09-11 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_schoolsubscriptionpayment_academic_year_and_more'),
        ('mobile_api', '0003_studentactivation_academic_year_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='RevokedToken',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('token_jti', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='معرف التوكن الفريد')),
                        ('revoked_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبطال')),
                        ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء الأصلي')),
                    ],
                    options={
                        'verbose_name': 'توكن مبطل',
                        'verbose_name_plural': 'قائمة التوكنات المبطلة',
                        'db_table': 'mobile_api_revokedtoken',
                    },
                ),
            ],
            database_operations=[]
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_assignments', to='core.schoolsettings', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='schoolnews',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_news', to='core.schoolsettings', verbose_name='المدرسة'),
        ),
    ]
